export const IS_USER_AUTH='IS_USER_AUTH';
export const AUTH_USER='AUTH_USER';

export const GET_PROJECTS='GET_PROJECTS';
export const SELECT_PROJECT='SELECT_PROJECT';
export const NEW='NEW';
export const POST_PROJECT='POST_PROJECT';
export const EDIT_PROJECT='EDIT_PROJECT';
export const UPDATE_PROJECT='UPDATE_PROJECT';
export const GET_PROJECTS_LENGTH='GET_PROJECTS_LENGTH';
export const UPDATE_PROJECT_DATA='UPDATE_PROJECT_DATA';
export const GET_PROJECT='GET_PROJECT';